# alpine doesn't work
FROM node:23-bullseye-slim
WORKDIR /app

# Copy only package.json + lockfile first (better cache)
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
