apiVersion: apps/v1
kind: Deployment
metadata:
    name: backend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: backend
    template:
        metadata:
            labels:
                app: backend
        spec:
            containers:
                - name: backend
                  image: ghcr.io/tyih985/campus_explorer-backend:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 4321
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 4321
                      initialDelaySeconds: 3
                      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: backend
spec:
    type: ClusterIP
    selector:
        app: backend
    ports:
        - port: 4321
          targetPort: 4321
          protocol: TCP
