apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
spec:
    replicas: 1
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: ghcr.io/tyih985/campus_explorer-frontend:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 80
                  readinessProbe:
                      httpGet:
                          path: /
                          port: 80
                      initialDelaySeconds: 3
                      periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
    type: NodePort
    selector:
        app: frontend
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30080
